version: '3.9'

services:
  db:
    image: postgres
    restart: always
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example